env:
  browser: true
  es2021: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
  - 'prettier'
  - 'better-styled-components'
rules:
  {
    no-console: warn,
    no-debugger: warn,
    semi: ['error', 'never'],
    quotes: ['error', 'single'],
    prettier/prettier: error,
    "react/react-in-jsx-scope": "off",
    "react/jsx-filename-extension": [ 1, { "extensions": [ ".js", ".jsx", ".ts", ".tsx" ] } ],
    "better-styled-components/sort-declarations-alphabetically": 2,
  }
